title: "Pattern And Projects"
description: "Home Automation mit PM-Methodik - ehrlich dokumentiert."
url: "https://PatternAndProjects.github.io"
baseurl: "/pattern-and-projects"
author: Franziska Gombert

theme: minima
logo: /assets/images/logo.svg
permalink: /:year/:month/:day/:title

exclude:
- Gemfile
- Gemfile.lock
