title: "Pattern And Projects"
description: "Schoen, dass du da bist. Auf meinem Blog teile ich mit dir meine persönlichen Projekte und setze alles in den Kontext des Projektmanagements und teste Projektmanagement Methoden aus."
url: "https://PatternAndProjects.github.io"
author: Franziska Gombert

theme: minima
logo: /assets/images/Logo.svg
permalink: /:year/:month/:day/:title

exclude:
- Gemfile
- Gemfile.lock
